-----------------DDL----------------------------------------

Create database SENAI_HROADS_TARDE;

use SENAI_HROADS_TARDE;


Create table TIPOHABILIDADE
(
		IdTIPO		INT PRIMARY KEY IDENTITY,
		NOME		VARCHAR(200)
);

create table HABILIDADE
(
		IdHABILIDADE	INT PRIMARY KEY IDENTITY,
		IdTIPO			INT	FOREIGN KEY REFERENCES TIPOHABILIDADE(IdTIPO),
		NOME			VARCHAR(200)
);

Create table CLASSE
(
		IdCLASSE		INT PRIMARY KEY IDENTITY,
		IdHABILIDADE	INT	FOREIGN KEY REFERENCES HABILIDADE(IdHABILIDADE),
		NOME			VARCHAR(200)
);

Create table PERSONAGEM
(
		IdPERSONAGEM    INT PRIMARY KEY IDENTITY,
		IdCLASSE		INT	FOREIGN KEY REFERENCES CLASSE(IdCLASSE),
		NOME			VARCHAR(200),
		MAXIMOVIDA		INT,
		MAXIMOVIDAMANA	INT,
		DATACRIACAO		DATE,
		DATATUALIZACAO	DATETIME
);