CREATE DATABASE Pessoa;

CREATE TABLE Pessoa
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL,
	Idade INT NOT NULL,
	Genero VARCHAR(200) NOT NULL
);

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	Numero INT NOT NULL,
	Operadora VARCHAR(200),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)
);

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	Usuario VARCHAR(200) NOT NULL,
	Senha VARCHAR(200) NOT NULL,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)
);

CREATE TABLE CNH
(
	IdCNH INT PRIMARY KEY IDENTITY,
	Numero INT NOT NULL,
	Categoria VARCHAR(8) NOT NULL,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa)
);